#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ---
test:
  name : saif
  workers:
    type: local
    number: 5
  rounds:
  # - label: Check Balance with Send Rate 300 [1].
  #   txNumber: 300
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 300
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 300 [2].
  #   txNumber: 300
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 300
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 300 [3].
  #   txNumber: 300
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 300
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 300 [4].
  #   txNumber: 300
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 300
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 300 [5].
  #   txNumber: 300
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 300
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js


  # - label: Check Balance with Send Rate 125 [1].
  #   txNumber: 125
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 125
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 125 [2].
  #   txNumber: 125
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 125
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 125 [3].
  #   txNumber: 125
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 125
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 125 [4].
  #   txNumber: 125
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 125
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  # - label: Check Balance with Send Rate 125 [5].
  #   txNumber: 125
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 125
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/checkbalance.js
  - label: Creating user with Send Rate 10 [1].
    txNumber: 1
    rateControl:
      type: fixed-rate
      opts:
        tps : 10
    arguments:
    callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 10 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 10 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 10 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 10 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 20 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 20 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 20 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 20 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 20 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 30 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 30 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 30 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 30 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 30 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 40 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 40 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 40 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 40 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 40 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 50 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 50 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 50 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 50 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
  # - label: Creating user with Send Rate 50 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #   callback: benchmarks/blockchainChatbot/signup.js
      


  # - label: Create a transaction with Send Rate 10 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 10 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 10 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 10 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 10 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 10
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 20 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 20 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 20 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 20 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 20 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 20
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 30 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 30 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 30 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 30 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 30 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 30
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 40 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 40 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 40 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 40 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 40 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 40
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 50 [1].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 50 [2].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 50 [3].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 50 [4].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js
  # - label: Create a transaction with Send Rate 50 [5].
  #   txNumber: 1
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps : 50
  #   arguments:
  #     assets: 1
  #   callback: benchmarks/blockchainChatbot/validation.js

  monitor:
    type:
    - docker
    - process
    docker:
      name:
      - all
    process:
    - command: node
      arguments: local-client.js
      multiOutput: avg
    interval: 1
